//************** AUTH TYPES *********************/
export const AUTH_LOADING = "AUTH_LOADING";
export const AUTH_FAILED = "AUTH_FAILED";
export const SIGN_IN = "SIGN_IN";
export const SIGN_OUT = "SIGN_OUT";
export const RESET_SIGN_UP = "RESET_SIGN_UP";

//************** JOB TYPES *********************/
export const GET_JOB_CATEGORIES = "GET_JOB_CATEGORIES";
export const GET_JOB_INDUSTRIES = "GET_JOB_INDUSTRIES";
export const GET_EDUCATION = "GET_EDUCATION";
export const GET_LOCATION_LIST = "GET_LOCATION_LIST";
export const SAVE_TEMPORARY_JOBPOST = "SAVE_TEMPORARY_JOBPOST";
export const UNSAVE_TEMPORARY_JOBPOST = "UNSAVE_TEMPORARY_JOBPOST";
export const CREATE_JOB = "CREATE_JOB";
export const DELETE_JOB = "DELETE_JOB";
export const UPDATE_JOB = "UPDATE_JOB";
export const SAVE_JOB = "SAVE_JOB";
export const APPLY_JOB = "APPLY_JOB";
export const ARCHIVE_JOB = "ARCHIVE_JOB";
export const GET_SINGLE_JOB = "GET_SINGLE_JOB";
export const GET_ALL_JOB = "GET_ALL_JOB";
export const GET_SAVED_JOB = "GET_SAVED_JOB";
export const GET_APPLIED_JOB = "GET_APPLIED_JOB";
export const GET_SELF_POSTED_JOB = "GET_SELF_POSTED_JOB";
export const FILTER_JOB = "FILTER_JOB";
export const UPLOAD_JOB_MEDIA = "UPLOAD_JOB_MEDIA";
export const RESET_JOB_STATE = "RESET_JOB_STATE";
export const RESET_TEMP_JOB_STATE = "RESET_TEMP_JOB_STATE";
export const INIT_JOB_STATE = "INIT_JOB_STATE";
export const GET_APPLIED_JOB_PERSON = "GET_APPLIED_JOB_PERSON";

//************** ANNOUNCEMENT TYPES *********************/
export const CREATE_ANNOUNCEMENT = "CREATE_ANNOUNCEMENT";
export const DELETE_ANNOUNCEMENT = "DELETE_ANNOUNCEMENT";
export const UPDATE_ANNOUNCEMENT = "UPDATE_ANNOUNCEMENT";
export const SAVE_ANNOUNCEMENT = "SAVE_ANNOUNCEMENT";
export const UNSAVE_ANNOUNCEMENT = "UNSAVE_ANNOUNCEMENT";
export const ARCHIVE_ANNOUNCEMENT = "ARCHIVE_ANNOUNCEMENT";
export const GET_SINGLE_ANNOUNCEMENT = "GET_SINGLE_ANNOUNCEMENT";
export const GET_ALL_ANNOUNCEMENT = "GET_ALL_ANNOUNCEMENT";
export const GET_ALL_ANNOUNCEMENT_OF_USER = "GET_ALL_ANNOUNCEMENT_OF_USER";
export const UPLOAD_ANNOUNCEMENT_MEDIA = "UPLOAD_ANNOUNCEMENT_MEDIA";

//************** USER TYPES *********************/
export const UPDATE_USER_PROFILE = "UPDATE_USER_PROFILE";
export const EDIT_USER_PROFILE = "EDIT_USER_PROFILE";
export const GET_OTHER_WORKERS = "GET_OTHER_WORKERS";
export const GET_SAVED_WORKERS = "GET_SAVED_WORKERS";
export const FILTERED_WORKERS = "FILTERED_WORKERS";
export const INIT_USER_STATE = "INIT_USER_STATE";
export const SAVE_WORKER = "SAVE_WORKER";
export const GET_DISTRICT = "GET_DISTRICT";
export const GET_DIVISION = "GET_DIVISION";
export const GET_THANA = "GET_THANA";

//************** PROJECT TYPES *********************/

export const VIEW_PROJECT = "VIEW_PROJECT";
export const CREATE_PROJECT = "CREATE_PROJECT";
export const DELETE_PROJECT = "DELETE_PROJECT";

//************** EMPLOYMENT TYPES *********************/
export const VIEW_EMPLOYMENT = "VIEW_EMPLOYMENT";
export const CREATE_EMPLOYMENT = "CREATE_EMPLOYMENT";
export const DELETE_EMPLOYMENT = "DELETE_EMPLOYMENT";

//************** EDUCATION TYPES *********************/
export const VIEW_EDUCATION = "VIEW_EDUCATION ";
export const CREATE_EDUCATION = "CREATE_EDUCATION";
export const DELETE_EDUCATION = "DELETE_EDUCATION";
//************** TRAINING TYPES *********************/
export const VIEW_TRAINING = "VIEW_TRAINING ";
export const CREATE_TRAINING = "CREATE_TRAINING";
export const DELETE_TRAINING = "DELETE_TRAINING";

//************** QUALIFICATIONS TYPES *********************/
export const VIEW_QUALIFICATION = "VIEW_QUALIFICATION ";
export const CREATE_QUALIFICATION = "CREATE_QUALIFICATION";
export const DELETE_QUALIFICATION = "DELETE_QUALIFICATION";

//************** SETTING TYPES *********************/
export const EDIT_PASSWORD = "EDIT_PASSWORD ";

//************** PREFERED_CATEGORIES TYPES *********************/
export const CREATE_PREFERED_CATEGORIES = "CREATE_PREFERED_CATEGORIES";
export const VIEW_PREFERED_CATEGORIES = "VIEW_PREFERED_CATEGORIES";
